/* eslint-disable @typescript-eslint/no-explicit-any */
import { suite, test, skip, strictEqual, ok, notOk, includes, notIncludes } from './runner';
import {
  coerceLazyFrameMode,
  DATALOG_RUNTIME_SOURCE,
  DEFAULT_LAZY_FRAME_MODE,
  LazyFrameMode,
  RUNTIME_CACHE_ATTR,
  RUNTIME_FILE_NAME,
  runtimeCallExpr,
} from '../pyRuntime';
import { buildLogMessage, buildPrintVarLogMessage, ExportConfig } from '../sasFormatter';
import { DataFrameAssignment } from '../pythonAnalyzer';
import { joinPath } from '../outputPaths';

declare function require(id: string): any;
declare const process: { pid: number; env: Record<string, string | undefined> };

const fs = require('fs');
const os = require('os');
const childProcess = require('child_process');

// ---------------------------------------------------------------------------
// Pure checks
// ---------------------------------------------------------------------------

suite('coerceLazyFrameMode', () => {
  test('accepts every documented mode', () => {
    for (const mode of ['off', 'schema', 'count', 'sample']) {
      strictEqual(coerceLazyFrameMode(mode), mode as LazyFrameMode);
    }
  });

  test('falls back to the default for anything else', () => {
    strictEqual(coerceLazyFrameMode('collect'), DEFAULT_LAZY_FRAME_MODE);
    strictEqual(coerceLazyFrameMode(undefined), DEFAULT_LAZY_FRAME_MODE);
    strictEqual(coerceLazyFrameMode(3), DEFAULT_LAZY_FRAME_MODE);
  });
});

suite('runtimeCallExpr', () => {
  const expr = runtimeCallExpr('datalog_emit', 'dict(a=1)', '/tmp/vscode-datalog/p/datalog_runtime.py');

  test('contains no braces, which logpoints would swallow', () => {
    notIncludes(expr, '{');
    notIncludes(expr, '}');
  });

  test('loads the module from the generated file', () => {
    includes(expr, "'/tmp/vscode-datalog/p/datalog_runtime.py'");
    includes(expr, 'exec(');
  });

  test('caches the namespace on builtins under a source-derived name', () => {
    includes(expr, RUNTIME_CACHE_ATTR);
    ok(/_datalog_rt_[0-9a-f]{8}/.test(RUNTIME_CACHE_ATTR), RUNTIME_CACHE_ATTR);
  });

  test('reuses the cached namespace instead of re-executing', () => {
    includes(expr, `getattr(_b, '${RUNTIME_CACHE_ATTR}', None) or `);
  });

  test('calls the requested entry point with the payload', () => {
    includes(expr, "['datalog_emit'](dict(a=1))");
  });
});

suite('DATALOG_RUNTIME_SOURCE', () => {
  test('defines both entry points', () => {
    includes(DATALOG_RUNTIME_SOURCE, 'def datalog_emit(payload):');
    includes(DATALOG_RUNTIME_SOURCE, 'def datalog_value(payload):');
  });

  test('resolves lazy schemas without collecting', () => {
    includes(DATALOG_RUNTIME_SOURCE, 'collect_schema');
  });

  test('says it is generated', () => {
    includes(DATALOG_RUNTIME_SOURCE, 'generated by the extension');
  });
});

// ---------------------------------------------------------------------------
// End to end against real Polars
//
// Builds the same logpoint messages the extension emits, converts each one the
// way pydevd does (convert_dap_log_message_to_expression) and evaluates it with
// a globals/locals pair, exactly like pydevd.handle_breakpoint_expression.
// ---------------------------------------------------------------------------

interface CaseSpec {
  name: string;
  message: string;
}

interface CaseResult {
  value?: string;
  exception?: string;
}

function pythonWithPolars(): string | null {
  for (const candidate of ['python3', 'python']) {
    try {
      const probe = childProcess.spawnSync(candidate, ['-c', 'import polars'], { encoding: 'utf8' });
      if (probe.status === 0) { return candidate; }
    } catch { /* try the next candidate */ }
  }
  return null;
}

const DRIVER_SOURCE = String.raw`import json
import sys

import builtins
import polars as pl

CASES_PATH, OUT_PATH, CACHE_ATTR = sys.argv[1], sys.argv[2], sys.argv[3]

BASE = pl.DataFrame(
    {
        "name": ["Alice", "Bob", "Charlie", "David", "Eve"],
        "age": [25, 30, 35, 40, 25],
        "city": ["NY", "London", "London", "Paris", "NY"],
        "score": [1.5, 2.0, 2.5, 3.0, 3.5],
    }
)


def to_expression(message):
    """Mirror pydevd's convert_dap_log_message_to_expression for one {expr}."""
    assert message.startswith("{") and message.endswith("}"), message
    inner = message[1:-1]
    assert "{" not in inner and "}" not in inner, "braces would break the logpoint"
    return repr("%s") + " % (" + inner + ",)"


def setup(name):
    """Return (extra globals, locals) for a case."""
    if name == "dataframe":
        return {}, {"input_df": BASE, "result_df": BASE.filter(pl.col("age") > 28)}
    if name.startswith("lazy_ok"):
        raw = BASE.lazy()
        return {}, {"raw_lf": raw, "out_lf": raw.filter(pl.col("city") == "London")}
    if name.startswith("lazy_bad"):
        raw = BASE.lazy()
        return {}, {"raw_lf": raw, "bad_lf": raw.select(pl.col("nmae"))}
    if name == "missing_out":
        return {}, {}
    if name == "missing_input":
        return {}, {"joined_df": BASE}
    if name == "global_only":
        return {"global_df": BASE}, {}
    if name == "series":
        return {}, {"col_df": BASE.get_column("age")}
    if name == "big":
        return {}, {"big_df": pl.DataFrame({"i": list(range(50))})}
    if name == "timestamped":
        return {}, {"stamp_df": BASE}
    if name == "value_dict":
        return {}, {
            "settings": {
                "path": "/data/in.csv",
                "rows": 12,
                "cols": ["a", "b", "c", "d", "e", "f", "g"],
                "ages": BASE.get_column("age"),
            }
        }
    if name == "value_int":
        return {}, {"row_count": 42}
    if name == "value_frame":
        return {}, {"sample_df": BASE}
    if name == "value_lazy":
        return {}, {"lazy_view": BASE.lazy()}
    raise AssertionError("unknown setup " + name)


results = {}
for case in json.load(open(CASES_PATH)):
    extra_globals, frame_locals = setup(case["name"])
    frame_globals = {"__builtins__": builtins, "pl": pl}
    frame_globals.update(extra_globals)
    try:
        expression = to_expression(case["message"])
        results[case["name"]] = {"value": eval(expression, frame_globals, frame_locals)}
    except BaseException as exc:  # noqa: BLE001 - reported back to the test
        results[case["name"]] = {"exception": type(exc).__name__ + ": " + str(exc)}

results["__meta__"] = {
    "cached": hasattr(builtins, CACHE_ATTR),
    "polars": pl.__version__,
}
with open(OUT_PATH, "w", encoding="utf-8") as handle:
    json.dump(results, handle)
`;

function runIntegration(): { results: Record<string, CaseResult>; dir: string } | null {
  const python = pythonWithPolars();
  if (!python) { return null; }

  const dir = joinPath(os.tmpdir(), `datalog-selftest-${process.pid}`);
  const worklib = joinPath(dir, 'worklib');
  const logFile = joinPath(dir, 'plog.log');
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(joinPath(dir, RUNTIME_FILE_NAME), DATALOG_RUNTIME_SOURCE, 'utf8');

  const config = (overrides: Partial<ExportConfig> = {}): ExportConfig => ({
    exportSamples: true,
    sampleRows: 1000,
    outputFolderAbsPath: worklib,
    logFileAbsPath: logFile,
    logTimestampLines: false,
    runtimeFileAbsPath: joinPath(dir, RUNTIME_FILE_NAME),
    lazyFrames: 'sample',
    ...overrides,
  });

  const assignment = (
    varName: string,
    sourceText: string,
    inputVars: string[],
    location: string
  ): DataFrameAssignment => ({
    varName,
    sourceText,
    range: { startLine: 0, endLine: 0 },
    inputVars,
    logLine: 1,
    location,
  });

  const cases: CaseSpec[] = [
    {
      name: 'dataframe',
      message: buildLogMessage(
        assignment('result_df', 'result_df = input_df.filter(pl.col("age") > 28)', ['input_df'], 'etl.py:12'),
        config()
      ),
    },
    {
      name: 'lazy_ok_sample',
      message: buildLogMessage(
        assignment('out_lf', 'out_lf = raw_lf.filter(pl.col("city") == "London")', ['raw_lf'], 'etl.py:20'),
        config({ lazyFrames: 'sample' })
      ),
    },
    {
      name: 'lazy_ok_schema',
      message: buildLogMessage(
        assignment('out_lf', 'out_lf = raw_lf.filter(pl.col("city") == "London")', ['raw_lf'], 'etl.py:20'),
        config({ lazyFrames: 'schema', exportSamples: false })
      ),
    },
    {
      name: 'lazy_ok_count',
      message: buildLogMessage(
        assignment('out_lf', 'out_lf = raw_lf.filter(pl.col("city") == "London")', [], 'etl.py:20'),
        config({ lazyFrames: 'count', exportSamples: false })
      ),
    },
    {
      name: 'lazy_ok_off',
      message: buildLogMessage(
        assignment('out_lf', 'out_lf = raw_lf.filter(pl.col("city") == "London")', [], 'etl.py:20'),
        config({ lazyFrames: 'off', exportSamples: false })
      ),
    },
    {
      name: 'lazy_bad_schema',
      message: buildLogMessage(
        assignment('bad_lf', 'bad_lf = raw_lf.select(pl.col("nmae"))', ['raw_lf'], 'etl.py:30'),
        config({ lazyFrames: 'schema' })
      ),
    },
    {
      name: 'lazy_bad_sample',
      message: buildLogMessage(
        assignment('bad_lf', 'bad_lf = raw_lf.select(pl.col("nmae"))', [], 'etl.py:30'),
        config({ lazyFrames: 'sample' })
      ),
    },
    {
      name: 'missing_out',
      message: buildLogMessage(assignment('ghost_df', 'ghost_df = build()', [], 'etl.py:40'), config()),
    },
    {
      name: 'missing_input',
      message: buildLogMessage(
        assignment('joined_df', 'joined_df = ghost_df.filter(x)', ['ghost_df'], 'etl.py:41'),
        config()
      ),
    },
    {
      name: 'global_only',
      message: buildLogMessage(assignment('global_df', 'global_df = pl.read_csv("g")', [], 'etl.py:50'), config()),
    },
    {
      name: 'series',
      message: buildLogMessage(assignment('col_df', 'col_df = base_df["age"]', [], 'etl.py:55'), config()),
    },
    {
      name: 'big',
      message: buildLogMessage(
        assignment('big_df', 'big_df = pl.DataFrame(range(50))', [], 'etl.py:60'),
        config({ sampleRows: 10 })
      ),
    },
    {
      name: 'timestamped',
      message: buildLogMessage(
        assignment('stamp_df', 'stamp_df = pl.read_csv("a")', [], 'etl.py:70'),
        config({ logTimestampLines: true, exportSamples: false })
      ),
    },
    { name: 'value_dict', message: buildPrintVarLogMessage('settings', config()) },
    { name: 'value_int', message: buildPrintVarLogMessage('row_count', config()) },
    { name: 'value_frame', message: buildPrintVarLogMessage('sample_df', config()) },
    { name: 'value_lazy', message: buildPrintVarLogMessage('lazy_view', config({ lazyFrames: 'sample' })) },
  ];

  const casesPath = joinPath(dir, 'cases.json');
  const resultsPath = joinPath(dir, 'results.json');
  const driverPath = joinPath(dir, 'driver.py');
  fs.writeFileSync(casesPath, JSON.stringify(cases), 'utf8');
  fs.writeFileSync(driverPath, DRIVER_SOURCE, 'utf8');

  const run = childProcess.spawnSync(
    python,
    [driverPath, casesPath, resultsPath, RUNTIME_CACHE_ATTR],
    { encoding: 'utf8' }
  );
  if (run.status !== 0) {
    throw new Error(`driver failed (${run.status}):\n${run.stdout}\n${run.stderr}`);
  }
  return { results: JSON.parse(fs.readFileSync(resultsPath, 'utf8')), dir };
}

const integration = (() => {
  try {
    return runIntegration();
  } catch (err: unknown) {
    return { error: err instanceof Error ? err.message : String(err) };
  }
})();

function withResults(fn: (results: Record<string, CaseResult>, dir: string) => void): () => void {
  return () => {
    const value = integration as { results?: Record<string, CaseResult>; dir?: string; error?: string };
    if (value.error) { throw new Error(value.error); }
    fn(value.results!, value.dir!);
  };
}

function block(results: Record<string, CaseResult>, name: string): string {
  const result = results[name];
  if (!result) { throw new Error(`no result for case "${name}"`); }
  if (result.exception) { throw new Error(`case "${name}" raised ${result.exception}`); }
  return result.value ?? '';
}

if (integration === null) {
  suite('Datalog runtime against real Polars', () => {
    skip('python3 with polars is not available on this machine');
  });
} else {
  suite('Datalog runtime — DataFrames', withResults((results, dir) => {
    test('reports input and output shapes SAS-style', () => {
      const text = block(results, 'dataframe');
      includes(text, '===DATALOG=== etl.py:12');
      includes(text, 'result_df = input_df.filter(pl.col("age") > 28)');
      includes(text, 'Input dataframe "input_df" has 5 rows and 4 columns.');
      includes(text, 'New dataframe "result_df" has 3 rows and 4 columns.');
    });

    test('block starts with a blank line, as before', () => {
      ok(block(results, 'dataframe').startsWith('\n===DATALOG==='), 'leading newline');
    });

    test('writes the sample CSV', () => {
      const csv = fs.readFileSync(joinPath(dir, 'worklib', 'result_df.csv'), 'utf8');
      includes(csv, 'name,age,city,score');
      strictEqual(csv.trim().split('\n').length, 4); // header + 3 rows
    });

    test('honours sampleRows and says the CSV is partial', () => {
      const text = block(results, 'big');
      includes(text, 'New dataframe "big_df" has 50 rows and 1 columns.');
      includes(text, 'NOTE: CSV holds the first 10 of 50 rows.');
      const csv = fs.readFileSync(joinPath(dir, 'worklib', 'big_df.csv'), 'utf8');
      strictEqual(csv.trim().split('\n').length, 11);
    });

    test('appends every block to the log file', () => {
      const logText = fs.readFileSync(joinPath(dir, 'plog.log'), 'utf8');
      includes(logText, 'New dataframe "result_df" has 3 rows and 4 columns.');
      includes(logText, 'New lazyframe "out_lf"');
    });

    test('writes the timestamp summary line when asked', () => {
      const logText: string = fs.readFileSync(joinPath(dir, 'plog.log'), 'utf8');
      ok(/\[\d\d:\d\d:\d\d\] stamp_df: 5 obs x 4 vars/.test(logText), 'timestamp line present');
    });

    test('a Series is reported without pretending to be a frame', () => {
      const text = block(results, 'series');
      includes(text, 'New value "col_df"');
      notIncludes(text, 'ERROR');
    });
  }));

  suite('Datalog runtime — LazyFrames', withResults((results, dir) => {
    test('sample mode reports real rows and columns', () => {
      const text = block(results, 'lazy_ok_sample');
      includes(text, 'Input lazyframe "raw_lf" has 5 rows and 4 columns.');
      includes(text, 'New lazyframe "out_lf" has 2 rows and 4 columns.');
    });

    test('sample mode writes a CSV for a LazyFrame', () => {
      const csv = fs.readFileSync(joinPath(dir, 'worklib', 'out_lf.csv'), 'utf8');
      includes(csv, 'London');
      strictEqual(csv.trim().split('\n').length, 3); // header + 2 rows
    });

    test('schema mode gives columns without collecting rows', () => {
      const text = block(results, 'lazy_ok_schema');
      includes(text, 'New lazyframe "out_lf" has 4 columns (rows not collected).');
      notIncludes(text, 'ERROR');
    });

    test('count mode gives rows without a CSV', () => {
      includes(block(results, 'lazy_ok_count'), 'New lazyframe "out_lf" has 2 rows and 4 columns.');
      notOk(fs.existsSync(joinPath(dir, 'worklib', 'out_lf_count.csv')), 'no extra CSV');
    });

    test('off mode reports nothing about the frame', () => {
      includes(block(results, 'lazy_ok_off'), 'New lazyframe "out_lf" has unknown size.');
    });

    test('schema mode surfaces a bad column reference at the assignment', () => {
      const text = block(results, 'lazy_bad_schema');
      includes(text, 'bad_lf = raw_lf.select(pl.col("nmae"))');
      includes(text, 'ERROR: lazyframe "bad_lf" failed to evaluate: ColumnNotFoundError');
      includes(text, 'nmae');
      includes(text, 'Input lazyframe "raw_lf" has 4 columns (rows not collected).');
    });

    test('sample mode surfaces the same error without raising', () => {
      const text = block(results, 'lazy_bad_sample');
      includes(text, 'ERROR: lazyframe "bad_lf" failed to evaluate: ColumnNotFoundError');
    });

    test('a failed LazyFrame gets no CSV', () => {
      notOk(fs.existsSync(joinPath(dir, 'worklib', 'bad_lf.csv')), 'no CSV for a broken frame');
    });

    test('errors are logged so they can be found later', () => {
      const logText = fs.readFileSync(joinPath(dir, 'plog.log'), 'utf8');
      includes(logText, 'ERROR: lazyframe "bad_lf" failed to evaluate');
    });
  }));

  suite('Datalog runtime — out-of-scope captures', withResults((results) => {
    test('an unbound output name is reported, not fatal', () => {
      const text = block(results, 'missing_out');
      includes(text, '"ghost_df" is not in scope on this line');
      notIncludes(text, 'NameError');
    });

    test('an unbound input does not lose the rest of the block', () => {
      const text = block(results, 'missing_input');
      includes(text, '"ghost_df" is not in scope on this line');
      includes(text, 'New dataframe "joined_df" has 5 rows and 4 columns.');
    });

    test('a module-level frame is found from a function frame', () => {
      includes(block(results, 'global_only'), 'New dataframe "global_df" has 5 rows and 4 columns.');
    });
  }));

  suite('Datalog runtime — printed values', withResults((results) => {
    test('plain values keep their repr', () => {
      strictEqual(block(results, 'value_int'), '\n===DATALOG=== row_count=42');
    });

    test('dictionaries stay compact', () => {
      const text = block(results, 'value_dict');
      includes(text, "'path': '/data/in.csv'");
      includes(text, "'rows': 12");
      includes(text, 'more items');
      includes(text, "Series(name='age', len=5");
    });

    test('a printed DataFrame shows its shape and table', () => {
      const text = block(results, 'value_frame');
      includes(text, 'dataframe with 5 rows and 4 columns');
      includes(text, 'Alice');
    });

    test('a printed LazyFrame is described instead of dumped', () => {
      const text = block(results, 'value_lazy');
      includes(text, 'lazyframe with 5 rows and 4 columns');
    });
  }));

  suite('Datalog runtime — module loading', withResults((results) => {
    test('the module is cached on builtins after the first hit', () => {
      const meta = (results as unknown as { __meta__: { cached: boolean } }).__meta__;
      ok(meta.cached, 'cache attribute set');
    });

    test('no case raised out of the logpoint', () => {
      for (const [name, result] of Object.entries(results)) {
        if (name === '__meta__') { continue; }
        notOk((result as CaseResult).exception, `${name}: ${(result as CaseResult).exception ?? ''}`);
      }
    });
  }));
}
