import { normalizePathForPython, pyStringExpr, shortHash } from './pyExpr';

export type LazyFrameMode = 'off' | 'schema' | 'count' | 'sample';

export const LAZY_FRAME_MODES: LazyFrameMode[] = ['off', 'schema', 'count', 'sample'];

export const DEFAULT_LAZY_FRAME_MODE: LazyFrameMode = 'sample';

export function coerceLazyFrameMode(value: unknown): LazyFrameMode {
  return LAZY_FRAME_MODES.includes(value as LazyFrameMode)
    ? (value as LazyFrameMode)
    : DEFAULT_LAZY_FRAME_MODE;
}

export const RUNTIME_FILE_NAME = 'datalog_runtime.py';

/**
 * Python helper module written to disk by the extension and loaded once per
 * debug session by the generated logpoints.
 *
 * Keeping the logic here rather than inline in each logpoint means:
 *  - logpoint expressions stay short, so debugpy compiles them quickly;
 *  - LazyFrame handling can use real statements (try/except) instead of
 *    nested conditional expressions;
 *  - the file is readable, so users can see exactly what runs in their process.
 */
export const DATALOG_RUNTIME_SOURCE = String.raw`"""Runtime helpers for the "Datalog for Polars" VS Code extension.

This file is generated by the extension and rewritten whenever logpoints are
refreshed, so local edits are lost. It is imported by the logpoints Datalog
places in your code: each one calls datalog_emit() or datalog_value() with a
payload dict, gets back the text shown in the Debug Console, and the same text
is appended to the Datalog log file.

Nothing here mutates your data. LazyFrames are only executed when the
vscode-datalog.lazyFrames setting asks for it ("count" runs a row count,
"sample" also collects the first N rows).
"""

MAX_ERROR_CHARS = 600
MAX_ERROR_LINES = 6
DICT_ENTRY_LIMIT = 8
ITEM_LIMIT = 5


def _polars():
    try:
        import polars
    except Exception:
        return None
    return polars


def describe_error(exc):
    """One-line summary plus indented detail lines, capped in size."""
    raw = str(exc).replace("\r", "")
    lines = [line.strip() for line in raw.split("\n") if line.strip()]
    if not lines:
        lines = [repr(exc)]
    truncated = len(lines) > MAX_ERROR_LINES
    if truncated:
        lines = lines[:MAX_ERROR_LINES]
    text = type(exc).__name__ + ": " + lines[0]
    for line in lines[1:]:
        text += "\n    " + line
    if truncated:
        text += "\n    ..."
    return text[:MAX_ERROR_CHARS]


def is_missing(value):
    """Captures use NotImplemented for names that were not in scope."""
    return value is NotImplemented


def is_dataframe(value):
    return hasattr(value, "shape") and hasattr(value, "write_csv")


def is_lazyframe(value):
    return hasattr(value, "collect") and not hasattr(value, "shape")


def lazy_schema(frame):
    """Resolve a LazyFrame schema without executing the query."""
    if hasattr(frame, "collect_schema"):
        return frame.collect_schema()
    return frame.schema


def lazy_height(frame):
    """Row count for a LazyFrame. Runs the plan, but only aggregates."""
    polars = _polars()
    if polars is not None and hasattr(polars, "len"):
        return int(frame.select(polars.len()).collect().item())
    return int(frame.collect().height)


def frame_info(value, lazy_mode="schema", sample_rows=0):
    """Describe a Polars frame.

    Returns a dict with kind ("dataframe", "lazyframe" or "value"), rows, cols,
    error (a describe_error() string when inspection failed) and collected (a
    materialised DataFrame when one was produced).
    """
    info = dict(kind="value", rows=None, cols=None, error=None, collected=None)
    if is_missing(value):
        info["kind"] = "missing"
        return info
    if is_dataframe(value):
        info["kind"] = "dataframe"
        try:
            info["rows"] = int(value.shape[0])
            info["cols"] = int(value.shape[1])
        except Exception as exc:
            info["error"] = describe_error(exc)
        return info
    if is_lazyframe(value):
        info["kind"] = "lazyframe"
        _fill_lazy_info(value, lazy_mode, sample_rows, info)
        return info
    shape = getattr(value, "shape", None)
    if isinstance(shape, tuple) and len(shape) == 2:
        info["rows"] = shape[0]
        info["cols"] = shape[1]
    return info


def _fill_lazy_info(frame, lazy_mode, sample_rows, info):
    if lazy_mode == "off":
        return

    # Schema resolution alone catches most authoring mistakes (missing or
    # misspelled columns, bad dtypes) without executing the query.
    try:
        info["cols"] = len(lazy_schema(frame))
    except Exception as exc:
        info["error"] = describe_error(exc)
        return
    if lazy_mode == "schema":
        return

    if lazy_mode == "sample" and sample_rows > 0:
        try:
            collected = frame.head(sample_rows).collect()
        except Exception as exc:
            info["error"] = describe_error(exc)
            return
        info["collected"] = collected
        if collected.height < sample_rows:
            # The head covered the whole frame, so this row count is exact and
            # we can skip a second pass over the data.
            info["rows"] = collected.height
            return

    try:
        info["rows"] = lazy_height(frame)
    except Exception as exc:
        info["error"] = describe_error(exc)


def frame_label(info):
    kind = info["kind"]
    if kind == "dataframe":
        return "dataframe"
    if kind == "lazyframe":
        return "lazyframe"
    return "value"


def shape_phrase(info):
    rows = info["rows"]
    cols = info["cols"]
    if rows is None and cols is None:
        return "unknown size"
    if rows is None:
        return str(cols) + " columns (rows not collected)"
    if cols is None:
        return str(rows) + " rows"
    return str(rows) + " rows and " + str(cols) + " columns"


def _frame_lines(role, name, info):
    if info["kind"] == "missing":
        return [role + ' "' + name + '" is not in scope on this line, so Datalog could not read it.']
    lines = [role + " " + frame_label(info) + ' "' + name + '" has ' + shape_phrase(info) + "."]
    if info["error"]:
        lines.append('ERROR: ' + frame_label(info) + ' "' + name + '" failed to evaluate: ' + info["error"])
    return lines


def export_csv(payload, info, value):
    """Write the sample CSV. Returns the path written, or None."""
    csv_dir = payload.get("csv_dir") or ""
    if not csv_dir:
        return None
    frame = info["collected"]
    if frame is None and info["kind"] == "dataframe":
        frame = value
    if frame is None or not hasattr(frame, "write_csv"):
        return None
    import os

    rows = payload.get("sample_rows") or 0
    stem = payload.get("csv_name") or "datalog_output"
    os.makedirs(csv_dir, exist_ok=True)
    path = os.path.join(csv_dir, stem + ".csv")
    frame.head(rows).write_csv(path)
    return path


def append_log(path, text):
    if not path:
        return
    handle = open(path, "a", encoding="utf-8")
    try:
        handle.write(text)
    finally:
        handle.close()


def _timestamp_line(payload, info):
    import datetime

    rows = "?" if info["rows"] is None else str(info["rows"])
    cols = "?" if info["cols"] is None else str(info["cols"])
    stamp = datetime.datetime.now().strftime("[%H:%M:%S] ")
    return stamp + str(payload.get("out_name") or "?") + ": " + rows + " obs x " + cols + " vars"


def _emit(payload):
    lazy_mode = payload.get("lazy_mode") or "schema"
    sample_rows = payload.get("sample_rows") or 0

    header = "===DATALOG==="
    location = payload.get("location") or ""
    if location:
        header = header + " " + location
    lines = [header]
    source = payload.get("source") or ""
    if source:
        lines.extend(source.split("\n"))

    for name, value in payload.get("inputs") or []:
        lines.extend(_frame_lines("Input", name, frame_info(value, lazy_mode, sample_rows)))

    out = payload.get("out")
    out_name = payload.get("out_name") or "?"
    out_info = frame_info(out, lazy_mode, sample_rows)
    lines.extend(_frame_lines("New", out_name, out_info))

    written = None
    try:
        written = export_csv(payload, out_info, out)
    except Exception as exc:
        lines.append('ERROR: could not write CSV for "' + out_name + '": ' + describe_error(exc))
    if written and sample_rows and out_info["rows"] is not None and out_info["rows"] > sample_rows:
        lines.append(
            "NOTE: CSV holds the first " + str(sample_rows) + " of " + str(out_info["rows"]) + " rows."
        )

    block = "\n" + "\n".join(lines)
    log_path = payload.get("log_path") or ""
    if log_path:
        prefix = ""
        if payload.get("timestamps"):
            prefix = _timestamp_line(payload, out_info) + "\n"
        append_log(log_path, prefix + block + "\n")
    return block


def datalog_emit(payload):
    """Entry point for DataFrame/LazyFrame assignment logpoints."""
    try:
        return _emit(payload)
    except Exception as exc:  # never break the debug session
        return "\n===DATALOG=== internal error: " + describe_error(exc)


def _preview_seq(seq, limit):
    try:
        items = list(seq[:limit])
    except Exception:
        try:
            items = list(seq)[:limit]
        except Exception:
            return repr(seq)
    try:
        total = len(seq)
    except Exception:
        total = len(items)
    suffix = "" if total <= limit else ", ... " + str(total - limit) + " more items"
    return "[" + ", ".join(repr(item) for item in items) + suffix + "]"


def _preview_value(value):
    if hasattr(value, "to_list") and not isinstance(value, (str, bytes, bytearray)):
        name = getattr(value, "name", None)
        try:
            total = len(value)
        except Exception:
            total = "?"
        try:
            values = value.to_list()[:ITEM_LIMIT]
        except Exception:
            values = []
        suffix = ""
        if total != "?" and total > ITEM_LIMIT:
            suffix = ", ... " + str(total - ITEM_LIMIT) + " more items"
        details = []
        if name is not None:
            details.append("name=" + repr(name))
        details.append("len=" + str(total))
        details.append("values=[" + ", ".join(repr(item) for item in values) + suffix + "]")
        return type(value).__name__ + "(" + ", ".join(details) + ")"
    if isinstance(value, (list, tuple)):
        open_ch, close_ch = ("[", "]") if isinstance(value, list) else ("(", ")")
        preview = _preview_seq(value, ITEM_LIMIT)
        return open_ch + preview[1:-1] + close_ch
    return repr(value)


def datalog_fmt(value, lazy_mode="schema", sample_rows=0):
    """Compact rendering of a printed value."""
    if is_missing(value):
        return "<not in scope on this line>"
    if is_dataframe(value) or is_lazyframe(value):
        info = frame_info(value, lazy_mode, sample_rows)
        text = frame_label(info) + " with " + shape_phrase(info)
        if info["error"]:
            return text + "\nERROR: " + info["error"]
        table = value if is_dataframe(value) else info["collected"]
        if table is not None:
            return text + "\n" + str(table)
        return text
    if not isinstance(value, dict):
        return _preview_value(value)
    items = list(value.items())
    shown = items[:DICT_ENTRY_LIMIT]
    omitted = len(items) - len(shown)
    lines = ["{"]
    for index, pair in enumerate(shown):
        key, item = pair
        comma = "," if index < len(shown) - 1 or omitted > 0 else ""
        lines.append("  " + repr(key) + ": " + _preview_value(item) + comma)
    if omitted > 0:
        lines.append("  ... " + str(omitted) + " more entries")
    lines.append("}")
    return "\n".join(lines)


def datalog_value(payload):
    """Entry point for print(var) logpoints."""
    try:
        name = payload.get("name") or "?"
        rendered = datalog_fmt(
            payload.get("value"),
            payload.get("lazy_mode") or "schema",
            payload.get("sample_rows") or 0,
        )
        block = "\n===DATALOG=== " + name + "=" + rendered
        append_log(payload.get("log_path") or "", block + "\n")
        return block
    except Exception as exc:
        return "\n===DATALOG=== internal error: " + describe_error(exc)
`;

/** Cache key changes with the runtime source so an upgraded extension reloads it. */
export const RUNTIME_CACHE_ATTR = `_datalog_rt_${shortHash(DATALOG_RUNTIME_SOURCE)}`;

/**
 * Build an expression that loads (and process-caches) the runtime module, then
 * calls `fnName` with `payloadExpr`.
 */
export function runtimeCallExpr(
  fnName: string,
  payloadExpr: string,
  runtimeFileAbsPath: string
): string {
  const pathExpr = pyStringExpr(normalizePathForPython(runtimeFileAbsPath));
  const attr = pyStringExpr(RUNTIME_CACHE_ATTR);
  const namespace =
    `(lambda _b=__import__('builtins'): getattr(_b, ${attr}, None) or ` +
    `(lambda _ns=dict(), _p=${pathExpr}: (` +
    `exec(_b.compile(_b.open(_p, 'r', encoding='utf-8').read(), _p, 'exec'), _ns), ` +
    `setattr(_b, ${attr}, _ns), _ns)[-1])())()`;
  return `${namespace}[${pyStringExpr(fnName)}](${payloadExpr})`;
}
